version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: secretstash-postgres
    environment:
      POSTGRES_DB: secretstash
      POSTGRES_USER: secretstash
      POSTGRES_PASSWORD: secretstash
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U secretstash"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
